# Generated by Django 2.1.15 on 2020-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0002_auto_20200609_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='quanxian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=20)),
                ('jon_code', models.CharField(max_length=20)),
                ('job_name', models.CharField(max_length=20)),
            ],
        ),
    ]
