# Generated by Django 2.1.15 on 2020-06-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0003_quanxian'),
    ]

    operations = [
        migrations.AddField(
            model_name='quanxian',
            name='level',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
