# Generated by Django 2.1.15 on 2020-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0008_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
