# Generated by Django 2.1.15 on 2020-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0011_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
