# Generated by Django 2.1.15 on 2020-06-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0014_wuliu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wenzi',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
