# Generated by Django 2.1.15 on 2020-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0016_sku_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='imageUrl',
            field=models.BooleanField(max_length=100, null=True),
        ),
    ]
