# Generated by Django 2.1.15 on 2020-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0018_auto_20200619_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=40)),
                ('add', models.CharField(max_length=40)),
                ('note', models.CharField(max_length=200)),
                ('salesman', models.CharField(max_length=40)),
                ('create_time', models.CharField(max_length=40)),
                ('examine', models.CharField(max_length=40)),
                ('examine_time', models.CharField(max_length=40)),
            ],
        ),
    ]
