# Generated by Django 2.1.15 on 2020-06-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0021_auto_20200620_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='order_key',
            field=models.CharField(default='', max_length=20),
        ),
    ]
