# Generated by Django 2.1.15 on 2020-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0022_order_del_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_del',
            name='lianchang',
            field=models.IntegerField(default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order_del',
            name='size',
            field=models.FloatField(default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order_del',
            name='total_num',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
    ]
