# Generated by Django 2.1.15 on 2020-06-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0023_auto_20200620_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_del',
            name='create_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order_del',
            name='end_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
