# Generated by Django 2.1.15 on 2020-06-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0026_order_del_order_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='picture',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
