# Generated by Django 2.1.15 on 2020-07-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0027_order_del_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='order_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
