# Generated by Django 2.1.15 on 2020-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0029_auto_20200715_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='salesman',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
