# Generated by Django 2.1.15 on 2020-07-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0030_order_del_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='date',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
