# Generated by Django 2.1.15 on 2020-07-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0032_order_del_draw_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.IntegerField(default=0)),
                ('user_code', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('order_code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('item_code', models.CharField(max_length=20, null=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('total_num', models.IntegerField(default=0)),
                ('packing_num', models.IntegerField(default=0)),
                ('wuliu', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('words', models.CharField(max_length=30)),
                ('lianchang', models.IntegerField(default=0, max_length=20, null=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
