# Generated by Django 2.1.15 on 2020-07-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0033_auto_20200719_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='packing_num',
            field=models.IntegerField(default=0),
        ),
    ]
