# Generated by Django 2.1.15 on 2020-07-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0037_auto_20200721_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_del',
            name='code_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='roles_del',
            name='job_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='roles_del',
            name='level',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='roles_del',
            name='jon_code',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
