# Generated by Django 2.1.15 on 2020-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0041_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack_method',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
