# Generated by Django 2.1.15 on 2020-08-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0042_pack_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='pack_method',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
