# Generated by Django 2.1.15 on 2020-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0043_order_del_pack_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='radio',
            field=models.CharField(default='1', max_length=2, null=True),
        ),
    ]
