# Generated by Django 2.1.15 on 2020-08-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0044_user_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='quanxian',
            name='sort',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
