# Generated by Django 2.1.15 on 2020-08-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0045_quanxian_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='radio',
            field=models.CharField(default='1', max_length=4, null=True),
        ),
    ]
