# Generated by Django 2.1.15 on 2020-08-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0047_auto_20200810_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_del',
            name='sort',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
