# Generated by Django 2.1.15 on 2020-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0050_order_del_pi_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw_pi',
            name='status',
            field=models.CharField(default='未画图', max_length=10, null=True),
        ),
    ]
