# Generated by Django 2.1.15 on 2020-08-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0051_draw_pi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='draw_name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order_del',
            name='draw_time',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order_del',
            name='draw_user',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
