# Generated by Django 2.1.15 on 2020-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0052_auto_20200811_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='print_status',
            field=models.CharField(default='未打印', max_length=30),
        ),
    ]
