# Generated by Django 2.1.15 on 2020-08-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0054_remove_order_del_ruku_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='sign',
            field=models.CharField(default='', max_length=30),
        ),
    ]
