# Generated by Django 2.1.15 on 2020-08-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0055_order_del_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_del',
            name='sign',
        ),
    ]
