# Generated by Django 2.1.15 on 2020-08-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0056_remove_order_del_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='draw_again_time',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order_del',
            name='print_time',
            field=models.CharField(default='未打印', max_length=30),
        ),
    ]
