# Generated by Django 2.1.15 on 2020-08-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0057_auto_20200813_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_del',
            name='print_time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
