# Generated by Django 2.1.15 on 2020-08-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0058_auto_20200813_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='draw_price',
            field=models.FloatField(default=0),
        ),
    ]
