# Generated by Django 2.1.15 on 2020-08-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0059_auto_20200813_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehous_Del',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.CharField(default='', max_length=20)),
                ('item_code', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('skutype', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('num', models.IntegerField(max_length=10)),
                ('total_num', models.IntegerField(default=0, max_length=10, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(default='未审核', max_length=20)),
                ('create_user', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehousing',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=40, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('create_time', models.CharField(max_length=40, null=True)),
                ('examine', models.CharField(max_length=40, null=True)),
                ('examine_time', models.CharField(max_length=40, null=True)),
                ('create_user', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order_del',
            name='print_time',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='sku',
            name='barcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
