# Generated by Django 2.1.15 on 2020-08-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0061_auto_20200815_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehous_del',
            name='unit',
            field=models.CharField(default='', max_length=20),
        ),
    ]
