# Generated by Django 2.1.15 on 2020-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0062_warehous_del_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('people', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=220, null=True)),
                ('note', models.CharField(max_length=220, null=True)),
                ('create_date', models.CharField(max_length=20, null=True)),
                ('create_user', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
