# Generated by Django 2.1.15 on 2020-08-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0063_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
