# Generated by Django 2.1.15 on 2020-08-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0065_cl_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_sku',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
