# Generated by Django 2.1.15 on 2020-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0066_cl_sku_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehous_del',
            old_name='skutype',
            new_name='format',
        ),
        migrations.AddField(
            model_name='warehous_del',
            name='date',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
