# Generated by Django 2.1.15 on 2020-08-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0068_auto_20200817_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousing',
            old_name='supplier',
            new_name='supplier_ware',
        ),
    ]
