# Generated by Django 2.1.15 on 2020-08-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0069_auto_20200817_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousing',
            name='type',
            field=models.CharField(default='入库', max_length=40, null=True),
        ),
    ]
