# Generated by Django 2.1.15 on 2020-08-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0070_warehousing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('item_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=20, null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('stock_num', models.IntegerField()),
            ],
        ),
    ]
