# Generated by Django 2.1.15 on 2020-08-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0071_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
