# Generated by Django 2.1.15 on 2020-08-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0072_auto_20200817_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_num',
            field=models.IntegerField(default=0),
        ),
    ]
