# Generated by Django 2.1.15 on 2020-08-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0073_order_total_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_del',
            name='size',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
