# Generated by Django 2.1.15 on 2020-08-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0074_auto_20200825_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw_pi',
            name='add',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='draw_pi',
            name='complete_time',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='draw_pi',
            name='draw_user',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='draw_pi',
            name='order_level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='draw_pi',
            name='total_num',
            field=models.IntegerField(default=0),
        ),
    ]
