# Generated by Django 2.1.15 on 2020-09-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0075_auto_20200829_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_level',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
