# Generated by Django 2.1.15 on 2020-09-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0076_order_order_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='update_time',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='update_user',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
