# Generated by Django 2.1.15 on 2020-09-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0077_auto_20200908_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='draw_status',
            field=models.CharField(default='未画图', max_length=10, null=True),
        ),
    ]
