# Generated by Django 2.1.15 on 2020-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0078_order_draw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='未审核', max_length=10, null=True),
        ),
    ]
