# Generated by Django 2.1.15 on 2020-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0079_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pi_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
