# Generated by Django 2.1.15 on 2020-09-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0081_draw_pi_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='sku_style',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
