# Generated by Django 2.1.15 on 2020-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0083_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='update_status',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
