# Generated by Django 2.1.15 on 2020-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0084_order_del_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw_pi',
            name='print_status',
            field=models.CharField(default='未打印', max_length=10, null=True),
        ),
    ]
