# Generated by Django 2.1.15 on 2020-09-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaijaing', '0087_auto_20200926_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_del',
            name='print_user',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
